# Generated by Django 4.2.15 on 2024-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
