# Generated by Django 4.2.15 on 2024-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_analysis", "0003_dailytechnicalindicators"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailytechnicalindicators",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
